name: Generate scss vars from tokens and copy
on: [push]

jobs:
  build_tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npx token-transformer input/design-tokens.json _variables
      - run: node build.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build tokens
          token: ${{ secrets.GH_PAT }} 

  copy_tokens:
    runs-on: ubuntu-latest
    needs: [build_tokens]
    steps:
      - uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          src_branch: main
          src_path: output/scss/.
          dst_owner: undp
          dst_repo_name: design-system
          dst_branch: issue-995-design-tokens
          dst_path: src/css/.
          username: vern-gora
          email: danvern99@gmail.com
          commit_message: copy scss tokens
